### ISSUE TITLE
Problem: DIPs are not automatically uploaded to the interface

### ISSUE THREAD

**Issue by kellyannewithane** [CCA-Public/dip-access-interface#93] opened 2018-08-24 16:07 UTC
From user stories (processing archivist, round 2)

As a Processing Archivist, I want DIPs to upload to the interface automatically after being created by Automation Tools during the Archivematica ingest process, so that I do not need to manually upload each DIP.

**Comment by jraddaoui** [comment] 2018-08-28 21:47
Duplicate of #2.

**Closed by jraddaoui** 2018-08-28 21:47 UTC
Labels: round2
