### ISSUE TITLE
Problem: user accounts are separate from institutional domain accounts

### ISSUE THREAD

**Issue by kellyannewithane** [CCA-Public/dip-access-interface#97] opened 2018-08-24 16:44 UTC
From user stories (IT, round 2)

-As local IT, I want all user accounts to be tied to institutional domain accounts, not to be handled separately.

**Comment by jraddaoui** [comment] 2018-08-28 23:28
Duplicate of #19.

**Closed by jraddaoui** 2018-08-28 23:28 UTC
Labels: round2
